DROP TABLE IF EXISTS sports;  
CREATE TABLE sports(
sportsId INTEGER NOT NULL AUTO_INCREMENT,
noOfPlayers INTEGER NOT NULL,
sportsName VARCHAR(256) NOT NULL,
sportsType VARCHAR(256) NOT NULL,
PRIMARY KEY (sportsId)
);
DROP TABLE IF EXISTS event;  
CREATE TABLE event(
eventId INTEGER NOT NULL AUTO_INCREMENT,
eventDate VARCHAR(256) NOT NULL,
eventName VARCHAR(256) NOT NULL,
noOfSlots INTEGER NOT NULL,
sportsName VARCHAR(256) NOT NULL,
PRIMARY KEY (eventId)
);